Show command line upon failure of antibody_graft
A test for the existance of the expected output file is performed
prior to the attempt to rename it. If that file is not existing,
then the command line for the execution of antibody.py is printed
and the script terminates.

This is apparently required since exceptions cought have not
triggered a non-zero return value, as in

ERROR: Unable to open weights/patch file. None of (./)pre_talaris_2013_standard.wts or (./)pre_talaris_2013_standard.wts.wts or /storage/projects/rosetta/rosetta-3.5/rosetta_database/scoring/weights/pre_talaris_2013_standard.wts or /storage/projects/rosetta/rosetta-3.5/rosetta_database/scoring/weights/pre_talaris_2013_standard.wts.wts exist
ERROR:: Exit from: src/core/scoring/ScoreFunction.cc line: 2967
caught exception

[ERROR] EXCN_utility_exit has been thrown from: src/core/scoring/ScoreFunction.cc line: 2967
ERROR: Unable to open weights/patch file. None of (./)pre_talaris_2013_standard.wts or (./)pre_talaris_2013_standard.wts.wts or /storage/projects/rosetta/rosetta-3.5/rosetta_database/scoring/weights/pre_talaris_2013_standard.wts or /storage/projects/rosetta/rosetta-3.5/rosetta_database/scoring/weights/pre_talaris_2013_standard.wts.wts exist

moeller@twin1b:/tmp/details $ echo $?
0